stages:
  - ci
  - cd


ci:
  stage: ci
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install -y curl
    - apt-get install -y openjdk-11-jdk-headless 
    - java -version 
    - echo "Installing Flutter"
    - curl -sL https://raw.githubusercontent.com/suborbital/flutter/master/install.sh 
    - echo "Deleting dependencies"
    - flutter clean
    - echo "Getting dependencies"
    - flutter pub get
    - echo "Running tests"
    - flutter test
    - echo "Building APK"
    - flutter build apk --release --build-number=${CI_PIPELINE_ID}
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk

cd:
  stage: cd
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y curl
    - apt-get update && apt-get install -y npm
    - npm install -g firebase-tools
    - echo "Downloading Android build"
    - artifacts download --name android-release
    - echo "Distributing app to Firebase"
    - echo "$FIREBASE_TOKEN" | tr -d '\r' > firebase.token  # Remove potential carriage return
    - firebase appdistribution:distribute app-release.apk \
        --app "$FIREBASE_ANDROID_ID" \
        --release-notes "Hello GDG" \
        --groups "tester" \
        --token < firebase.token
  only:
    - main

variables:
  FIREBASE_ANDROID_ID: $FIREBASE_ANDROID_ID
  FIREBASE_TOKEN:  $FIREBASE_TOKEN