stages:
  - ci
  - cd
  - build


build: 
    image: mobiledevops/flutter-sdk-image:3.19.4
    stage: ci
    script: 
        - git config --global --add safe.directory /home/mobiledevops/.flutter-sdk

        - echo "Dart Repair"
        - dart pub cache clean
        
        - echo "Running Clean Packages"
        - flutter clean
        
        - echo "Running Get Packages"
        - flutter pub get

        - echo "Running tests"
        - flutter test

cd:
  stage: cd
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y curl
    - apt-get update && apt-get install -y npm
    - npm install -g firebase-tools
    - echo "Downloading Android build"
    - artifacts download --name android-release
    - echo "Distributing app to Firebase"
    - echo "$FIREBASE_TOKEN" | tr -d '\r' > firebase.token  # Remove potential carriage return
    - firebase appdistribution:distribute app-release.apk \
        --app "$FIREBASE_ANDROID_ID" \
        --release-notes "Hello GDG" \
        --groups "tester" \
        --token < firebase.token
  only:
    - main

variables:
  FIREBASE_ANDROID_ID: $FIREBASE_ANDROID_ID
  FIREBASE_TOKEN:  $FIREBASE_TOKEN