stages:
  - ci
  - cd
  - build

variables:
  FIREBASE_ANDROID_ID: $FIREBASE_ANDROID_ID
  FIREBASE_TOKEN:  $FIREBASE_TOKEN
  SUPABASE_KEY: $SUPABASE_KEY
  SUPABASE_URL: $SUPABASE_URL

build: 
    image: mobiledevops/flutter-sdk-image:3.19.4
    stage: ci
    script: 
        - git config --global --add safe.directory /home/mobiledevops/.flutter-sdk

        - echo "Dart Repair"
        - dart pub cache clean
        
        - echo "Running Clean Packages"
        - flutter clean
        
        - echo "Running Get Packages"
        - flutter pub get

        - echo "Running tests"
        - flutter test

        - echo "Building project"
        - flutter build --release --dart-define=supabaseUrl=$SUPABASE_URL --dart-define=supabaseKey=$SUPABASE_KEY


distributeFirebase:
  stage: cd
  image: node:latest
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export JAVA_HOME="/usr/bin/java"
    - apt-get update -y && apt-get install wget -y
  dependencies:
    - assembleRelease
    
  script:
    - npm install -g firebase-tools
    - if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app $FIREBASE_ANDROID_ID --release-notes-file release-notes.txt --groups "tester" --token "$FIREBASE_TOKEN"; fi
  only:
    - main


